image: gitpod/workspace-full-vnc

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: ROS Base Installation
    command: |
      bash /workspace/avai/install_ros.sh
      gp sync-done ros
  
  - name: Additional Tools Installation
    command: |
      gp sync-await ros
      sudo apt-get install -yq \
        ros-foxy-gazebo-* \
        ros-foxy-cartographer \
        ros-foxy-cartographer-ros \
        ros-foxy-navigation2 \
        ros-foxy-nav2-bringup
      source ~/.bashrc
      sudo apt-get install -yq \
        ros-foxy-dynamixel-sdk \
        ros-foxy-turtlebot3-msgs \
        ros-foxy-turtlebot3 \
        python3-rosdep2