image: gitpod/workspace-full-vnc

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: ROS Installation
    command: bash /workspace/avai/install_ros.sh