
image: gitpod/workspace-full-vnc

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: ROS Installation
    init: bash /workspace/avai/scripts/install_ros.sh
    command: gp sync-done ros_installation

  - name: Addition Tools Installation
    before: gp sync-await ros_installation
    init: bash /workspace/avai/scripts/install_tools.sh
    command: gp sync-done tools_installation

  - name: Initial Build Workspace
    before: gp sync-await tools_installation
    init: bash /workspace/avai/scripts/initial_build.sh
    command: gp sync-done initial_build
vscode:
  extensions:
    - ms-python.python
    - redhat.vscode-xml
